"""
Django settings for line_bot_dict project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vwv(ngc6!))pr^jtew#zw5%#)&1pggw+mjnt@+=z-paj#q*fl+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'c3ab-2001-b400-e2df-4a04-c0bc-241d-7413-6855.ngrok.io',
    'fd7c-2001-b400-e2d8-4783-99fa-9fcb-c62d-b509.ngrok.io',
    '667f-2001-b400-e285-1336-6138-241a-1696-6b7a.ngrok.io',
    '75e3-2001-b011-4009-10eb-384a-281d-2025-33f0.ngrok.io',
    '1f56-2001-b011-4009-10eb-384a-281d-2025-33f0.ngrok.io',
    '6a15-2001-b011-4009-10eb-f97f-5c9c-7ee0-5ec7.ngrok.io',
    '378a-2001-b011-4009-10eb-8cf7-6e6e-2af9-984d.ngrok.io',
    '48f7-2001-b400-e275-cce6-e86f-6ce5-8d4e-cde5.ngrok.io',
    '9e2b-2001-b400-e275-cce6-e86f-6ce5-8d4e-cde5.ngrok.io',
    'a0d7-2001-b011-4009-1b41-d40-f773-7ffc-e076.ngrok.io',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dict',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'line_bot_dict.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'line_bot_dict.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
        'NAME': 'line_bot_vb',  #資料庫名稱
        'USER': 'postgres',  #資料庫帳號
        'PASSWORD': 'daniel13579',  #資料庫密碼
        'HOST': 'localhost',  #Server(伺服器)位址
        'PORT': '5432'  #PostgreSQL Port號
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LINE_CHANNEL_ACCESS_TOKEN = 'bcUBifHDdIfz+t1UP80wzC+plsuOYXRz4gkdUgQXRfOBQrnDFOnAQWi+Es7JA+zWke+i+LIR1P5ATTakX1IKovnyyF4iq/kGlukwSuJ3YrtfGFuclX1vK7egh0wWE+HLeF9vyp6aYpStdmMhbfrM9QdB04t89/1O/w1cDnyilFU='
 
LINE_CHANNEL_SECRET = '2ab84b8e694ce69ea747200ad3ddd333'